### ISSUE TITLE
error start zap-cli

### ISSUE THREAD

**Issue by sergelacroute** [Grunny/zap-cli#11]
I failed to run zap-cli despite an installation from source

I try all the examples in the documentation unsuccessfully error
sample error

zap-cli --api-key 12345 quick-scan --self-contained -o '-config api.key=12345' -s xss http://127.0.0.1/
[INFO]            Starting ZAP daemon
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 9, in <module>
    load_entry_point('zapcli==0.2.1', 'console_scripts', 'zap-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-i686/egg/zapcli/cli.py", line 246, in quick_scan
  File "build/bdist.linux-i686/egg/zapcli/zap_helper.py", line 77, in start
IOError: [Errno 2] No such file or directory: u'/zap/zap.log'

zap-cli start --start-options '-config api.key=12345'
[INFO]            Starting ZAP daemon
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 9, in <module>
    load_entry_point('zapcli==0.2.1', 'console_scripts', 'zap-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-i686/egg/zapcli/cli.py", line 102, in start_zap_daemon
  File "build/bdist.linux-i686/egg/zapcli/zap_helper.py", line 77, in start
IOError: [Errno 2] No such file or directory: u'/zap/zap.log'

**Comment by Grunny** [comment]
Hi @sergelacroute! Thanks for the report, and sorry for the delayed response. This is because the path to ZAP provided was the default (`/zap`) and wasn't where you have ZAP installed. You can set the location where ZAP is installed on your system using either the `--zap-path` command line parameter or make things easier by setting it by default using the `ZAP_PATH` environment variable.

I have added a more useful error message when this happens which tells you how to fix it in https://github.com/Grunny/zap-cli/pull/12 It's available in master, so if you update, you should get a more useful error message than the stack trace you currently see. :) Let me know if you run into any other problems.

**Comment by sergelacroute** [comment]
thank you for your reply and work
I updated with git and zap zap-cli and reinstall everything
I still encounter errors

zap-cli --zap-path /usr/local/bin/  --api-key 12345 quick-scan --self-contained -o '-config api.key=12345' -s xss http://127.0.0.1/
[INFO]            Starting ZAP daemon
[ERROR]           ZAP was not found in the path "/usr/local/bin/". You can set the path to where ZAP is installed on your system using the --zap-path command line parameter or by default using the ZAP_PATH environment variable.

zap-cli   --api-key 12345 quick-scan --self-contained -o '-config api.key=12345' -s xss http://127.0.0.1/
[INFO]            Starting ZAP daemon
[ERROR]           ZAP was not found in the path "/zap". You can set the path to where ZAP is installed on your system using the --zap-path command line parameter or by default using the ZAP_PATH environment variable.

root@fakessh:~# ls -alih /usr/local/bin/zap*
38016989 -rwxr-xr-x 1 root staff 214 mai   31 16:24 /usr/local/bin/zap
38020954 -rwxr-xr-x 1 root staff 298 mai   31 15:23 /usr/local/bin/zap-cli

there are still errors that prevented the operation

**Comment by sivassk7** [comment]
Check where zap installed path not the executable one
check by searching locate zap
mine it's under /snap/zaproxy/current
zap-cli --zap-path=/snap/zaproxy/current start
