### ISSUE TITLE
zap-cli not start

### ISSUE THREAD

**Issue by Ehsan-Abbaspour** [Grunny/zap-cli#17]
Hi
 i have an error when run this command:
root@kali:/home/zap-cli/zapcli# zap-cli /usr/bin/zaproxy  start
[INFO]            Starting ZAP daemon
[ERROR]           ZAP was not found in the path "/usr/bin". You can set the path to where ZAP is installed on your system using the --zap-path command line parameter or by default using the ZAP_PATH environment variable.

please help me

**Comment by Grunny** [comment]
Hi @Ehsan-Abbaspour! The `--zap-path` command line option, or the `ZAP_PATH` environment variable, should be set to the folder where the ZAP folder is that contains the file `zap.sh`, as that is the executable `zap-cli` currently looks for on Linux systems. So, if you set to the path where the ZAP folder is, it should work. If you installed ZAP from a package, then it will probably be [in the `/usr/share/zaproxy` folder](https://github.com/zaproxy/zaproxy/blob/19cd192cecd/build/debian/zap) for example. An example of setting the path via commandline would be `zap-cli --zap-path /usr/share/zaproxy start`.

**Comment by Ehsan-Abbaspour** [comment]
Hi @Grunny 
thanks very much :)
my problem solved, but when run this command: "  zap-cli quick-scan -s xss,sqli --spider -r -e "some_regex_pattern" http://127.0.0.1/ "  
i have this error:
-----------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 9, in <module>
    load_entry_point('zapcli==0.3.0', 'console_scripts', 'zap-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 406, in enable_policies
    zap_helper.enable_policies_by_ids(policy_ids)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 302, in enable_policies_by_ids
    self.zap.ascan.set_enabled_policies(policy_ids, apikey=self.api_key)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/ascan.py", line 243, in set_enabled_policies
    return next(self.zap._request(self.zap.base + 'ascan/action/setEnabledPolicies/', params).itervalues())
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 145, in _request
    return json.loads(self.urlopen(url + '?' + urllib.urlencode(get)))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
--------------------------------------------------
best regards :)

**Comment by Grunny** [comment]
That usually suggests ZAP isn't running. Is this after starting ZAP successfully (i.e. with the `start` command)? Can you try with the verbose option (i.e. `zap-cli --verbose quick-scan -s xss,sqli --spider -r -e "some_regex_pattern" http://127.0.0.1/`) and paste the output?

**Comment by Grunny** [comment]
Closing for now, let me know if you run into any other issues. :)
