### ISSUE TITLE
Cannot import ZAP Context 

### ISSUE THREAD

**Issue by pry0cc** [Grunny/zap-cli#45]
Hi, I have exported a context with owasp zap, and the file exported is an XML file.

When looking at the error given by zap-cli, it appears to be a JSON error, have contexts from zap-ui ever been JSON?  Or am I expected to encode it into JSON?

```
zap@Ghost3:/zap/raygun$ zap-cli context import auth.context 
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/commands/context.py", line 104, in context_import
    zap_helper.import_context(file_path)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 454, in import_context
    result = self.zap.context.import_context(file_path, apikey=self.api_key)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/context.py", line 108, in import_context
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'context/action/importContext/', {'contextFile': contextfile, 'apikey': apikey})))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 160, in _request
    return data.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by Grunny** [comment]
Hi @pry0cc! That error suggests the response from the ZAP API when you're trying to import it is incorrect. The only way I can reproduce is to misconfigure zap-cli to use the wrong port so it is requesting something other than ZAP (i.e. talking to a local Apache server instead of the ZAP API).

Do other commands work via zap-cli such as running scans, opening URLs, etc.? If not, can you verify that you have ZAP running and have set the right environment variables for ZAP_PORT and ZAP_API_KEY: https://github.com/Grunny/zap-cli#usage

**Comment by pry0cc** [comment]
Hi @Grunny! Thanks for the prompt response :)

I am using this in combination with a bash script, attempting to automate authenticated active scans. 

```
zap-cli context import /zap/raygun/auth.context
zap-cli open-url $URL
zap-cli spider --context-name $context --user-name $user $URL
zap-cli active-scan --recursive -c $context -u $user $URL
zap-cli quick-scan --recursive --spider -c $context -u $user $URL
```
From looking from that, you're absolutely right, I wasn't running the API. Thanks a tonne man :)
