### ISSUE TITLE
Unable to scan any url.

### ISSUE THREAD

**Issue by PrashanthPrabhabharan** [Grunny/zap-cli#46]
Hi,

I am trying to configure zap-cli in my windows 10 machine.
Steps : 
- Configured ZAP_PATH, ZAP_PORT, ZAP_URL in environment variable
- Cloned git project
- Installed python3.6.4 and set python in environment variable. Can run python anywhere using windows prompt
- Installed pip
- ran pip install --upgrade zapcli command
- Entering zap-cli in windows cmd:
``` 
C:\>zap-cli
Usage: zap-cli [OPTIONS] COMMAND [ARGS]...

  ZAP CLI v0.9.0 - A simple commandline tool for OWASP ZAP.

Options:
  --boring            Remove color from console output.
  -v, --verbose       Add more verbose debugging output.
  --zap-path TEXT     Path to the ZAP daemon. Defaults to /zap or the value of
                      the environment variable ZAP_PATH.
  -p, --port INTEGER  Port of the ZAP proxy. Defaults to 8090 or the value of
                      the environment variable ZAP_PORT.
  --zap-url TEXT      The URL of the ZAP proxy. Defaults to http://127.0.0.1
                      or the value of the environment variable ZAP_URL.
  --api-key TEXT      The API key for using the ZAP API if required. Defaults
                      to the value of the environment variable ZAP_API_KEY.
  --help              Show this message and exit.

Commands:
  active-scan  Run an Active Scan.
  ajax-spider  Run the AJAX Spider against a URL.
  alerts       Show alerts at the given alert level.
  context      Manage contexts for the current session.
  exclude      Exclude a pattern from all scanners.
  open-url     Open a URL using the ZAP proxy.
  policies     Enable or list a set of policies.
  quick-scan   Run a quick scan.
  report       Generate XML or HTML report.
  scanners     Enable, disable, or list a set of scanners.
  scripts      Manage scripts.
  session      Manage sessions.
  shutdown     Shutdown the ZAP daemon.
  spider       Run the spider against a URL.
  start        Start the ZAP daemon.
  status       Check if ZAP is running.
```
- But when I run the below command, I am getting error. Please let me know if anything is required
```
C:\>zap-cli quick-scan --self-contained --spider -r -s xss http://demo.testfire.net
[1m[36m[INFO]            [0mStarting ZAP daemon
[1m[33m[WARNING]         [0mZAP is already running on port 8090
[1m[36m[INFO]            [0mRunning a quick scan for http://demo.testfire.net
Traceback (most recent call last):
  File "C:\python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python36\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\python36\lib\site-packages\requests\packages\urllib3\util\retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: http://zap/JSON/ascan/action/disableAllScanners/?apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python36\Scripts\zap-cli-script.py", line 11, in <module>
    load_entry_point('zapcli==0.9.0', 'console_scripts', 'zap-cli')()
  File "C:\python36\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\python36\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\python36\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python36\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python36\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\python36\lib\site-packages\click\decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "C:\python36\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\python36\lib\site-packages\zapcli\cli.py", line 217, in quick_scan
    zap_helper.set_enabled_scanners(options['scanners'])
  File "C:\python36\lib\site-packages\zapcli\zap_helper.py", line 310, in set_enabled_scanners
    self.zap.ascan.disable_all_scanners(apikey=self.api_key)
  File "C:\python36\lib\site-packages\zapv2\ascan.py", line 284, in disable_all_scanners
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'ascan/action/disableAllScanners/', params)))
  File "C:\python36\lib\site-packages\zapv2\__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "C:\python36\lib\site-packages\zapv2\__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "C:\python36\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\python36\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python36\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\python36\lib\site-packages\requests\adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8090): Max retries exceeded with url: http://zap/JSON/ascan/action/disableAllScanners/?apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
```

**Comment by Grunny** [comment]
That seems like there's an issue connecting to ZAP on that port to proxy the requests. Are you able to successfully proxy through ZAP in your browser on port 8090? Just checking if the issue is specific to zap-cli.

**Comment by aynacisevda** [comment]
@Grunny I see same problem with zap-cli.I can open ZAP in my browser on port that is given.But take below error:

zap-cli start && zap-cli session load "C:\Users\sahip\OWASP ZAP\session\pixageone.session"
2019-07-30T07:13:37.4096768Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "C:\agents\KSPixageOneD1B1\_work\_temp\6ed5da86-ea82-4c9e-b89c-f43599e9626b.cmd""
2019-07-30T07:13:38.7407319Z [INFO]            Starting ZAP daemon
2019-07-30T07:13:47.3308454Z Traceback (most recent call last):
2019-07-30T07:13:47.3308767Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 600, in urlopen
2019-07-30T07:13:47.3308851Z     chunked=chunked)
2019-07-30T07:13:47.3308968Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 384, in _make_request
2019-07-30T07:13:47.3309039Z     six.raise_from(e, None)
2019-07-30T07:13:47.3309107Z   File "<string>", line 2, in raise_from
2019-07-30T07:13:47.3309191Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 380, in _make_request
2019-07-30T07:13:47.3309364Z     httplib_response = conn.getresponse()
2019-07-30T07:13:47.3309449Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1336, in getresponse
2019-07-30T07:13:47.3309512Z     response.begin()
2019-07-30T07:13:47.3309587Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 306, in begin
2019-07-30T07:13:47.3309681Z     version, status, reason = self._read_status()
2019-07-30T07:13:47.3309758Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 275, in _read_status
2019-07-30T07:13:47.3309827Z     raise RemoteDisconnected("Remote end closed connection without"
2019-07-30T07:13:47.3309916Z http.client.RemoteDisconnected: Remote end closed connection without response
2019-07-30T07:13:47.3315152Z 
2019-07-30T07:13:47.3315619Z During handling of the above exception, another exception occurred:
2019-07-30T07:13:47.3315675Z 
2019-07-30T07:13:47.3315784Z Traceback (most recent call last):
2019-07-30T07:13:47.3315858Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\adapters.py", line 449, in send
2019-07-30T07:13:47.3315952Z     timeout=timeout
2019-07-30T07:13:47.3316025Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 638, in urlopen
2019-07-30T07:13:47.3316109Z     _stacktrace=sys.exc_info()[2])
2019-07-30T07:13:47.3316181Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\util\retry.py", line 399, in increment
2019-07-30T07:13:47.3316245Z     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2019-07-30T07:13:47.3316336Z urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: http://zap/JSON/core/action/loadSession/?name=C%3A%5CUsers%5Csahip%5COWASP+ZAP%5Csession%5Cpixageone.session&apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-30T07:13:47.3319476Z 
2019-07-30T07:13:47.3319559Z During handling of the above exception, another exception occurred:
2019-07-30T07:13:47.3319594Z 
2019-07-30T07:13:47.3319696Z Traceback (most recent call last):
2019-07-30T07:13:47.3319762Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\Scripts\zap-cli-script.py", line 11, in <module>
2019-07-30T07:13:47.3319830Z     load_entry_point('zapcli==0.10.0', 'console_scripts', 'zap-cli')()
2019-07-30T07:13:47.3320277Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 664, in __call__
2019-07-30T07:13:47.3322228Z     return self.main(*args, **kwargs)
2019-07-30T07:13:47.3323007Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 644, in main
2019-07-30T07:13:47.3323323Z     rv = self.invoke(ctx)
2019-07-30T07:13:47.3323424Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 991, in invoke
2019-07-30T07:13:47.3323488Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-07-30T07:13:47.3323580Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 991, in invoke
2019-07-30T07:13:47.3323648Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-07-30T07:13:47.3323715Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 837, in invoke
2019-07-30T07:13:47.3323810Z     return ctx.invoke(self.callback, **ctx.params)
2019-07-30T07:13:47.3323880Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 464, in invoke
2019-07-30T07:13:47.3323952Z     return callback(*args, **kwargs)
2019-07-30T07:13:47.3324027Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\decorators.py", line 26, in new_func
2019-07-30T07:13:47.3324142Z     return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
2019-07-30T07:13:47.3324219Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 464, in invoke
2019-07-30T07:13:47.3324280Z     return callback(*args, **kwargs)
2019-07-30T07:13:47.3324585Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zapcli-0.10.0-py3.7.egg\zapcli\commands\session.py", line 49, in load_session
2019-07-30T07:13:47.3324697Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\core.py", line 308, in load_session
2019-07-30T07:13:47.3324789Z     return six.next(six.itervalues(self.zap._request(self.zap.base + 'core/action/loadSession/', {'name': name, 'apikey': apikey})))
2019-07-30T07:13:47.3324991Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\__init__.py", line 159, in _request
2019-07-30T07:13:47.3325096Z     data = self._request_api(url, get)
2019-07-30T07:13:47.3325211Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\__init__.py", line 149, in _request_api
2019-07-30T07:13:47.3325307Z     return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
2019-07-30T07:13:47.3325464Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 546, in get
2019-07-30T07:13:47.3325576Z     return self.request('GET', url, **kwargs)
2019-07-30T07:13:47.3325741Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 533, in request
2019-07-30T07:13:47.3326867Z     resp = self.send(prep, **send_kwargs)
2019-07-30T07:13:47.3327128Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 646, in send
2019-07-30T07:13:47.3327295Z     r = adapter.send(request, **kwargs)
2019-07-30T07:13:47.3327401Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\adapters.py", line 510, in send
2019-07-30T07:13:47.3327467Z     raise ProxyError(e, request=request)
2019-07-30T07:13:47.3327583Z requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: http://zap/JSON/core/action/loadSession/?name=C%3A%5CUsers%5Csahip%5COWASP+ZAP%5Csession%5Cpixageone.session&apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by AgrawalHimanshu** [comment]
Any update on this issue
