### ISSUE TITLE
Zap-cli connection refuse issue 

### ISSUE THREAD

**Issue by HUssain14** [Grunny/zap-cli#60]
facing below error while running zap-cli even define the port but still refusing the connection anything im missing here ? below is the error

```Accessing URL http://testhtml5.vulnweb.com/
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 102, in open_url
    zap_helper.open_url(url)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 132, in open_url
    self.zap.urlopen(url)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 124, in urlopen
    return requests.get(url, proxies=self.__proxies, verify=False, *args, **kwargs).text
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8030): Max retries exceeded with url: http://testhtml5.vulnweb.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f119c1e2b50>: Failed to establish a new connection: [Errno 111] Connection refused',)))```

**Comment by Grunny** [comment]
Closing in favour of #57 for now.
