### ISSUE TITLE
zap-cli quick-scan is not running. I need a help!

### ISSUE THREAD

**Issue by dakkarkey** [Grunny/zap-cli#71]
I have a difficulty installing and running zap-cli.
After several install attempts, I finally installed zap-cli via sudo, and the ZAP daemon ran successfully. My results are shown below.
```
$ sudo pip install --upgrade zapcli
....
$ sudo zap-cli --zap-path /usr/local/bin --api-key 1234567890 start
[INFO]            Starting ZAP daemon
$ sudo zap-cli --zap-path /usr/local/bin --api-key 1234567890 status
[INFO]            ZAP is running
```
However, if I try quick-scan with zap-cli, an error occurs.
What did I do wrong? I need your help, plz.
```
$ sudo zap-cli --zap-path /usr/local/bin --api-key 1234567890 quick-scan -s xss,sqli --spider -r -e "hacker" http://192.168.0.191
[INFO]            Running a quick scan for http://192.168.0.191
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 225, in quick_scan
    zap_helper.set_enabled_scanners(options['scanners'])
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 314, in set_enabled_scanners
    self.zap.ascan.disable_all_scanners()
  File "/usr/local/lib/python2.7/dist-packages/zapv2/ascan.py", line 284, in disable_all_scanners
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'ascan/action/disableAllScanners/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by Grunny** [comment]
That error is usually caused by the API key being incorrect. I'd suggest double checking the API key you're using with `zap-cli` is correct in the running version of ZAP.
