### ISSUE TITLE
Receive 'Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response' error with zap-cli at CI/CD pipeline

### ISSUE THREAD

**Issue by aynacisevda** [Grunny/zap-cli#82]
**Hi,
I am trying to add OWASP ZAP scanning at CI/CD pipeline (Azure DevOps Server) by using zap-cli.
Steps :
Configured ZAP_PATH, ZAP_PORT, ZAP_URL and PYTHON_HOME in environment variable

Add a task like this to start ZAP as daemon mode and load a session respectively:**
![image](https://user-images.githubusercontent.com/44896069/62120773-ea90b200-b2ca-11e9-9755-c21ce664f695.png)

**ZAP is started successfully but receive an error for session load:**

2019-07-30T07:13:35.6176537Z ##[section]Starting: Open OWASP ZAP daemon
2019-07-30T07:13:35.6531693Z ==============================================================================
2019-07-30T07:13:35.6531932Z Task         : Command Line
2019-07-30T07:13:35.6532046Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-07-30T07:13:35.6532111Z Version      : 2.142.1
2019-07-30T07:13:35.6532170Z Author       : Microsoft Corporation
2019-07-30T07:13:35.6532241Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-07-30T07:13:35.6532323Z ==============================================================================
2019-07-30T07:13:37.3416045Z Generating script.
2019-07-30T07:13:37.3417255Z Script contents:
2019-07-30T07:13:37.3424414Z zap-cli start && zap-cli session load "C:\Users\sahip\OWASP ZAP\session\pixageone.session"
2019-07-30T07:13:37.4096768Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "C:\agents\KSPixageOneD1B1\_work\_temp\6ed5da86-ea82-4c9e-b89c-f43599e9626b.cmd""
2019-07-30T07:13:38.7407319Z [INFO]            Starting ZAP daemon
2019-07-30T07:13:47.3308454Z Traceback (most recent call last):
2019-07-30T07:13:47.3308767Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 600, in urlopen
2019-07-30T07:13:47.3308851Z     chunked=chunked)
2019-07-30T07:13:47.3308968Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 384, in _make_request
2019-07-30T07:13:47.3309039Z     six.raise_from(e, None)
2019-07-30T07:13:47.3309107Z   File "<string>", line 2, in raise_from
2019-07-30T07:13:47.3309191Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 380, in _make_request
2019-07-30T07:13:47.3309364Z     httplib_response = conn.getresponse()
2019-07-30T07:13:47.3309449Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1336, in getresponse
2019-07-30T07:13:47.3309512Z     response.begin()
2019-07-30T07:13:47.3309587Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 306, in begin
2019-07-30T07:13:47.3309681Z     version, status, reason = self._read_status()
2019-07-30T07:13:47.3309758Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 275, in _read_status
2019-07-30T07:13:47.3309827Z     raise RemoteDisconnected("Remote end closed connection without"
2019-07-30T07:13:47.3309916Z http.client.RemoteDisconnected: Remote end closed connection without response
2019-07-30T07:13:47.3315152Z 
2019-07-30T07:13:47.3315619Z During handling of the above exception, another exception occurred:
2019-07-30T07:13:47.3315675Z 
2019-07-30T07:13:47.3315784Z Traceback (most recent call last):
2019-07-30T07:13:47.3315858Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\adapters.py", line 449, in send
2019-07-30T07:13:47.3315952Z     timeout=timeout
2019-07-30T07:13:47.3316025Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\connectionpool.py", line 638, in urlopen
2019-07-30T07:13:47.3316109Z     _stacktrace=sys.exc_info()[2])
2019-07-30T07:13:47.3316181Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3-1.24.3-py3.7.egg\urllib3\util\retry.py", line 399, in increment
2019-07-30T07:13:47.3316245Z     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2019-07-30T07:13:47.3316336Z urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: http://zap/JSON/core/action/loadSession/?name=C%3A%5CUsers%5Csahip%5COWASP+ZAP%5Csession%5Cpixageone.session&apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-30T07:13:47.3319476Z 
2019-07-30T07:13:47.3319559Z During handling of the above exception, another exception occurred:
2019-07-30T07:13:47.3319594Z 
2019-07-30T07:13:47.3319696Z Traceback (most recent call last):
2019-07-30T07:13:47.3319762Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\Scripts\zap-cli-script.py", line 11, in <module>
2019-07-30T07:13:47.3319830Z     load_entry_point('zapcli==0.10.0', 'console_scripts', 'zap-cli')()
2019-07-30T07:13:47.3320277Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 664, in __call__
2019-07-30T07:13:47.3322228Z     return self.main(*args, **kwargs)
2019-07-30T07:13:47.3323007Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 644, in main
2019-07-30T07:13:47.3323323Z     rv = self.invoke(ctx)
2019-07-30T07:13:47.3323424Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 991, in invoke
2019-07-30T07:13:47.3323488Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-07-30T07:13:47.3323580Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 991, in invoke
2019-07-30T07:13:47.3323648Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-07-30T07:13:47.3323715Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 837, in invoke
2019-07-30T07:13:47.3323810Z     return ctx.invoke(self.callback, **ctx.params)
2019-07-30T07:13:47.3323880Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 464, in invoke
2019-07-30T07:13:47.3323952Z     return callback(*args, **kwargs)
2019-07-30T07:13:47.3324027Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\decorators.py", line 26, in new_func
2019-07-30T07:13:47.3324142Z     return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
2019-07-30T07:13:47.3324219Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-4.0-py3.7.egg\click\core.py", line 464, in invoke
2019-07-30T07:13:47.3324280Z     return callback(*args, **kwargs)
2019-07-30T07:13:47.3324585Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zapcli-0.10.0-py3.7.egg\zapcli\commands\session.py", line 49, in load_session
2019-07-30T07:13:47.3324697Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\core.py", line 308, in load_session
2019-07-30T07:13:47.3324789Z     return six.next(six.itervalues(self.zap._request(self.zap.base + 'core/action/loadSession/', {'name': name, 'apikey': apikey})))
2019-07-30T07:13:47.3324991Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\__init__.py", line 159, in _request
2019-07-30T07:13:47.3325096Z     data = self._request_api(url, get)
2019-07-30T07:13:47.3325211Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_owasp_zap_v2.4-0.0.14-py3.7.egg\zapv2\__init__.py", line 149, in _request_api
2019-07-30T07:13:47.3325307Z     return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
2019-07-30T07:13:47.3325464Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 546, in get
2019-07-30T07:13:47.3325576Z     return self.request('GET', url, **kwargs)
2019-07-30T07:13:47.3325741Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 533, in request
2019-07-30T07:13:47.3326867Z     resp = self.send(prep, **send_kwargs)
2019-07-30T07:13:47.3327128Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\sessions.py", line 646, in send
2019-07-30T07:13:47.3327295Z     r = adapter.send(request, **kwargs)
2019-07-30T07:13:47.3327401Z   File "C:\Users\sahip2\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.20.1-py3.7.egg\requests\adapters.py", line 510, in send
2019-07-30T07:13:47.3327467Z     raise ProxyError(e, request=request)
2019-07-30T07:13:47.3327583Z requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: http://zap/JSON/core/action/loadSession/?name=C%3A%5CUsers%5Csahip%5COWASP+ZAP%5Csession%5Cpixageone.session&apikey= (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-30T07:13:47.4665030Z ##[error]Cmd.exe exited with code '1'.
2019-07-30T07:13:47.5348386Z ##[section]Finishing: Open OWASP ZAP daemon

**Comment by cfguimaraes** [comment]
@aynacisevda did you already take a look at owasp/zap2docker from docker hub?

**Comment by mydeveloperplanet** [comment]
This is probably caused due to the fact that you did not specifiy the API_KEY. As you can see in the URL, the API KEY parameter is empty. This can be solved by setting the ZAP_API_KEY env variable. You can find the API KEY in ZAP desktop via Tools - Options - API

**Comment by eliyahus** [comment]
@mydeveloperplanet thanks for this tip, it solved my issue
