### ISSUE TITLE
Dockerized ZAP Proxy throws error when executing zap-cli commands

### ISSUE THREAD

**Issue by ari-luokkala** [Grunny/zap-cli#92]
**Start ZAP proxy container:**
```
docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
```
**Execute zap-cli command in the running container**
```
docker exec zap zap-cli --verbose report -o /zap/reports/owasp-scan-report.html --output-format html
```
**Error occurs:**
```
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 621, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```
**Environment:**
4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Comment by ari-luokkala** [comment]
This might be actually fixed on ZAP Proxy side, so closing here.

**Comment by arthurakay** [comment]
Sorry to be dense, but what's going on with this issue exactly? I don't quite understand how/where/when this might see a fix

**Comment by ari-luokkala** [comment]
This is fixed in ZAP Proxy side in Dockerfiles:
https://github.com/zaproxy/zaproxy/issues/5818
